# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:9

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}{{ checksum "api/yarn.lock" }}{{ checksum "web/yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # install apps
      - run:
            command: |
              yarn install
              cd api
              yarn install
              cd ../web
              yarn install

      - save_cache:
          paths:
            - node_modules
            - api/node_modules
            - web/node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}{{ checksum "api/yarn.lock" }}{{ checksum "web/yarn.lock" }}

      # run apps
      - run:
            command: |
              cd api
              yarn prisma local start
              yarn prisma deploy

      - run:
            command: |
              cd web
              yarn build
              yarn start
            background: true

      - run:
            command: |
              cd api
              yarn build
              yarn start
            background: true

      # 🚧 TODO wait until apps are running
      # run tests!
      - run: yarn test
